data:
  #sentences_to_read_num: 100
  train_dataset: data/szeged-judit/*
  train_matrices: data/train_matrices
  random_seed: 448
  example_resolution: morpheme
  train_ratio: 0.8
  validation_ratio: 0.1
inference:
  batch_size: 128
  maximum_iterations: 64
  transducer_path: /userhome/student/peterng/programs/emMorph/hfst/hu.hfstol
network:
  embedding_size: 8
  hidden_layer_cell_type: LSTM
  hidden_layer_cells: 32
  hidden_layer_count: 4
  max_gradient_norm: 5
  max_source_sequence_length: 107
  max_target_sequence_length: 64
  window_length: 5
  dropout_keep_probability: 0.5
  activation: sigmoid
train:
  batch_size: 64
  epochs: 1000
  loss_optimizer: GradientDescentOptimizer
  loss_optimizer_kwargs: {}
  schedule:
    - {learning_rate: 1.0,    until_global_step: 500}
    - {learning_rate: 0.1,    until_global_step: 1000}
    - {learning_rate: 0.01,   until_global_step: 1500}
    - {learning_rate: 0.001,  until_global_step: 2000}
    - {learning_rate: 0.0001, until_global_step: 3000}
  shuffle_sentences: true
  shuffle_examples_in_batches: false