data:
  rebuild_vocabulary_file: false
  rows_to_read_num: null
  train_dataset: data/szeged-judit/*
  train_matrices: data/train_matrices
  random_seed: 448
  example_resolution: character
inference:
  batch_size: 128
  maximum_iterations: 64
  transducer_path: /userhome/student/peterng/emMorph/hfst/hu.hfstol
network:
  embedding_size: 8
  hidden_layer_cell_type: LSTM
  hidden_layer_cells: 128
  hidden_layer_count: 2
  max_gradient_norm: 3
  max_source_sequence_length: 107
  max_target_sequence_length: 64
  window_length: 5
  dropout_keep_probability: 0.8
  activation: relu
test:
  sentences_rate: 0.1
train:
  batch_size: 256
  decay_rate: 0.1
  decay_steps: 10000
  decay_type: piecewise_constant
  decaying_learning_rate: false
  early_stop_after_not_decreasing_loss_num: null
  epochs: 1000
  loss_optimizer: AdamOptimizer
#  loss_optimizer_kwargs:
#    momentum: 0.5
  save_modulo: 1
  shuffle_sentences: true
  shuffle_examples_in_batches: true
  starter_learning_rate: 0.001
