data:
  batch_size: 256
  example_resolution: character
  random_seed: 448
  train_dataset: data/szeged-judit/*
  train_matrices: data/train_matrices
  train_ratio: 0.8
  validation_ratio: 0.1
inference:
  beam_width: 3
  decoder_type: beam_search
  transducer_path: /userhome/student/peterng/programs/emMorph/hfst/hu.hfstol
network:
  activation: null
  dropout_keep_probability: 0.8
  embedding_size: 8
  hidden_layer_cell_type: LSTM
  hidden_layer_cells: 64
  hidden_layer_count: 2
  max_gradient_norm: 5
  max_source_sequence_length: 109
  max_target_sequence_length: 61
  window_length: 5
train:
  add_summary_modulo: 100
  epochs: 100000
  loss_optimizer: MomentumOptimizer
  loss_optimizer_kwargs:
    momentum: 0.5
  schedule:
  - learning_rate: 1.0
    until_global_step: 1000
  - learning_rate: 0.5
    until_global_step: 2000
  - learning_rate: 0.25
    until_global_step: 4000
  - learning_rate: 0.125
    until_global_step: 5000
  - learning_rate: 0.0625
    until_global_step: 16000
  - learning_rate: 0.03125
    until_global_step: 32000
  - learning_rate: 0.015625
    until_global_step: 64000
  - learning_rate: 0.0078125
    until_global_step: 128000
  - learning_rate: 0.00390625
    until_global_step: 256000
  - learning_rate: 0.001953125
    until_global_step: 512000
  - learning_rate: 0.0005
    until_global_step: 1024000
  - learning_rate: 0.00025
    until_global_step: 2048000
  - learning_rate: 0.000125
    until_global_step: 4048000
  shuffle_examples_in_batches: false
  shuffle_sentences: true
  validation_add_summary_modulo: 100
  validation_modulo: 1
